# Generated by Django 5.0.4 on 2025-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='icones_conquistas/'),
        ),
    ]
