# Generated by Django 5.0.4 on 2025-05-13 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0002_conquista_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacao',
            name='ultimo_login_diario',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
