# Generated by Django 5.0.4 on 2025-05-23 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direitoapp', '0002_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('etapa_atual', models.IntegerField(default=1)),
                ('finalizado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstudoDiarioResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_usuario', models.CharField(max_length=10)),
                ('correta', models.BooleanField()),
                ('estudo_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='estudodiario.estudodiario')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direitoapp.question')),
            ],
        ),
    ]
