# Generated by Django 5.1 on 2025-04-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direitoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('alternative_a', models.CharField(max_length=255)),
                ('alternative_b', models.CharField(max_length=255)),
                ('alternative_c', models.CharField(max_length=255)),
                ('alternative_d', models.CharField(max_length=255)),
                ('alternative_e', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
            ],
        ),
    ]
