# Generated by Django 5.0.4 on 2025-05-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direitoapp', '0003_customuser_bio_customuser_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
            ],
        ),
    ]
